### ISSUE TITLE
Download works But install doesn't

### ISSUE THREAD

**Issue by yoelsd** [vetruvet/ota-update-centre#10]
Hey,

Im using this wonderful OTA app for my S1 rom (2.3.6 based, semaphore kernel - CWM).
After the download the app reboots in to e3 recovery and now CWM, so the rom isn't installed.
It finds the file on the SD but can't flash is because its not CWM ! - Signature verification failed

RC4 by the way.

I would gladly appreciate any ideas to help fix this,

Yoel.

**Comment by HaiPBM** [comment]
+1 !!

**Comment by yoelsd** [comment]
Update :
I got the phone to Reset instead of enter E3, but that means users have to manually install every update :)

**Comment by vetruvet** [comment]
Sorry, I'm unfamiliar with Samsung's recovery process... I know HTC has
bootloader, recovery, and normal boot... what is Reset and what is E3?

**Comment by M3NTI0N** [comment]
If the OP does not come with more information we'll be forces to close this issue.
We can't fix issues without information and help from a person with the device.

Thanks for understanding.

Please if you want this fixed and the problem still exists report the issue again on:
https://github.com/OTAUpdateCenter/ota-update-centre/
