### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by mikrosmile** [vetruvet/ota-update-centre#3]
Actually Im not sure if that error causes by the unsigned rom.. I got this error

CWM V5.8.0.9
Finding update package
Opening update package
Verifying update package
E:signature verification failed
Installation aborted

When i try to install it manually from recovery than no problems.

Maybe try to disable in the app verification solve that problem? 

I tried four dofferent methods to check that error.. and there is a result - the same error

I used SmartApk tool which can sign zips
I used signed zip file - did not re-sogn it, used as it is
I re-sign zip
I used the kithcen for making roms to make a NEW zip file without any signatures. just.  put some apk files and that it and complie it to a rom, still the same problem..

Please check that, because i dont think that it is only me have such error.

Thank you very much.

**Comment by M3NTI0N** [comment]
This issue is closed cause noone else had this problem, without beeing able to fix it.
If any more of these issues will come without a fix, i will reopen this one.
