### ISSUE TITLE
WiFi prompt does not wait for action

### ISSUE THREAD

**Issue by NilsP** [vetruvet/ota-update-centre#4]
When starting app on phone and an update is available the WiFi off  warning pops up to either Exit, Ignore, or go to WiFi settings but immediately after that the download prompt comes up and hides the WiFi option.

In other words you never get the opportunity to decide on WiFi or not.

The expected result is you decide on WiFi then get the download prompt.

**Comment by vetruvet** [comment]
Fixed in RC4. Thank you for reporting
