### ISSUE TITLE
Force close without data connect

### ISSUE THREAD

**Issue by zyy757** [vetruvet/ota-update-centre#7]
app verison :rc-3
device:Motorola DROID2 GLOBAL 
ROM: stock 4.5.629

If I start otaupdater without a mobile data connect or only a wifi connect, the app will force close.
Only mobile data or both mobile data & wifi is OK

**Comment by M3NTI0N** [comment]
Also Confirmed on the Sensation.
But since you need data to check for updates, it's not as important as other bugs.

**Comment by vetruvet** [comment]
Fixed in RC4. Thank you for reporting
